spring.application.name=spring-boot
spring.datasource.url=jdbc:postgresql://localhost:5332/finfree
spring.datasource.username=${DB_USERNAME:finfree}
spring.datasource.password=${DB_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true